general:
  # Commands to run when the WM has started. This is useful for running a
  # script or launching another application.
  # Example: The below command launches Zebar.
  startup_commands: ["shell-exec zebar"]

  # Commands to run just before the WM is shutdown.
  # Example: The below command kills Zebar.
  shutdown_commands: ["shell-exec taskkill /IM zebar.exe /F"]

  # Commands to run after the WM config is reloaded.
  config_reload_commands: []

  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: false

  # Whether to switch back and forth between the previously focused
  # workspace when focusing the current workspace.
  toggle_workspace_on_refocus: false

  cursor_jump:
    # Whether to automatically move the cursor on the specified trigger.
    enabled: true

    # Trigger for cursor jump:
    # - 'monitor_focus': Jump when focus changes between monitors.
    # - 'window_focus': Jump when focus changes between windows.
    trigger: "monitor_focus"

  # How windows should be hidden when switching workspaces.
  # - 'cloak': Recommended. Hides windows with no animation.
  # - 'hide': Legacy method (v3.5 and earlier) that has a brief animation,
  # but has stability issues with some apps.
  hide_method: "cloak"

  # Affects which windows get shown in the native Windows taskbar. Has no
  # effect if `hide_method: 'hide'`.
  # - 'true': Show all windows (regardless of workspace).
  # - 'false': Only show windows from the currently shown workspaces.
  show_all_in_taskbar: false

gaps:
  # Whether to scale the gaps with the DPI of the monitor.
  scale_with_dpi: true

  # Gap between adjacent windows.
  inner_gap: "10px"

  # Gap between windows and the screen edge.
  outer_gap:
    top: "45px"
    right: "10px"
    bottom: "10px"
    left: "10px"

window_effects:
  # Visual effects to apply to the focused window.
  focused_window:
    # Highlight the window with a colored border.
    # ** Exclusive to Windows 11 due to API limitations.
    border:
      enabled: true
      color: "#8dbcff"

    # Remove the title bar from the window's frame. Note that this can
    # cause rendering issues for some applications.
    hide_title_bar:
      enabled: false

    # Change the corner style of the window's frame.
    # ** Exclusive to Windows 11 due to API limitations.
    corner_style:
      enabled: false
      # Allowed values: 'square', 'rounded', 'small_rounded'.
      style: "square"

    # Change the transparency of the window.
    transparency:
      enabled: false
      # Can be something like '95%' or '0.95' for slightly transparent windows.
      # '0' or '0%' is fully transparent (and, by consequence, unfocusable).
      opacity: "95%"

  # Visual effects to apply to non-focused windows.
  other_windows:
    border:
      enabled: true
      color: "#a1a1a1"
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: false
      style: "square"
    transparency:
      enabled: false
      opacity: "0%"

window_behavior:
  # New windows are created in this state whenever possible.
  # Allowed values: 'tiling', 'floating'.
  initial_state: "tiling"

  # Sets the default options for when a new window is created. This also
  # changes the defaults for when the state change commands, like
  # `set-floating`, are used without any flags.
  state_defaults:
    floating:
      # Whether to center floating windows by default.
      centered: true

      # Whether to show floating windows as always on top.
      shown_on_top: false

    fullscreen:
      # Maximize the window if possible. If the window doesn't have a
      # maximize button, then it'll be fullscreen'ed normally instead.
      maximized: false

      # Whether to show fullscreen windows as always on top.
      shown_on_top: false

workspaces:
  - name: "1"
    bind_to_monitor: 0
    # keep_alive: true

  - name: "2"
    # keep_alive: true

    # bind_to_monitor: 1

  - name: "3"
    # keep_alive: true

    # bind_to_monitor: 0

  - name: "4"
    # keep_alive: true

    # bind_to_monitor: 1

  - name: "5"
    # keep_alive: true

    # bind_to_monitor: 0

  # - name: "6"
  #   bind_to_monitor: 1

  # - name: "7"
  #   bind_to_monitor: 0

  # - name: "8"
  #   bind_to_monitor: 1

  # - name: "9"
  #   bind_to_monitor: 0

window_rules:
  # - commands: ["move --workspace 9"]
  #   match:
  #     - window_process: { equals: "KeePassXC" }

  - commands: ["ignore"]
    match:
      # Ignores any Zebar windows.
      - window_process: { equals: "zebar" }

      # Ignores picture-in-picture windows for browsers.
      - window_title:
          {
            regex: "[Pp]icture.in.[Pp]icture|ピクチャー(?: イン |イン)ピクチャー",
          }
        window_class: { regex: "Chrome_WidgetWin_1|MozillaDialogClass" }

      # Ignore rules for various 3rd-party apps.
      - window_process: { equals: "PowerToys" }
        window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }
      - window_process: { equals: "PowerToys" }
        window_title: { regex: ".*? - Peek" }
      - window_process: { equals: "Lively" }
        window_class: { regex: "HwndWrapper" }

      - window_process: { equals: "KeePassXC" }
        window_title: { regex: ".*? - KeePassXC|KeePassXC" }

      - window_process: { equals: "explorer" }
        window_title: { equals: "ファイル名を指定して実行" }

      - window_title: { equals: "コマンド パレット" }
        window_class: { equals: "WinUIDesktopWin32WindowClass" }

      - window_process: { equals: "StrokesPlus" }
        window_title: { equals: "Console" }
      - window_process: { equals: "VirtualBoxVM" }
        window_title: { equals: "仮想マシンを閉じる" }

      - window_process: { equals: "VeraCrypt" }

      - window_process: { equals: "MSPCManager" }
      - window_process: { equals: "mstsc" }
        window_title: { equals: "リモート デスクトップ接続" }

      - window_title: { equals: "Microsoft アカウント" }

      - window_title: { equals: "デバイスを追加する" }

  - commands: ["move --workspace 1", "focus --workspace 1"]
    match:
      - window_process: { equals: "firefox" }

  - commands: ["move --workspace 2", "focus --workspace 2"]
    match:
      - window_process: { equals: "Code" }

  - commands: ["move --workspace 3", "focus --workspace 3"]
    match:
      - window_process: { equals: "explorer" }

  - commands: ["move --workspace 4", "focus --workspace 4"]
    match:
      - window_process: { equals: "chrome" }

# PowerToys:
# Muhenkan -> Print Screen
binding_modes:
  # When enabled, the focused window can be resized via arrow keys or HJKL.
  - name: "resize"
    keybindings:
      - commands: ["resize --width -2%"]
        bindings: ["h", "left"]
      - commands: ["resize --width +2%"]
        bindings: ["l", "right"]
      - commands: ["resize --height +2%"]
        bindings: ["k", "up"]
      - commands: ["resize --height -2%"]
        bindings: ["j", "down"]
      # Press enter/escape to return to default keybindings.
      - commands: ["wm-disable-binding-mode --name resize"]
        bindings: ["escape", "enter"]

keybindings:
  # Shift focus in a given direction.
  # - commands: ["focus --direction left"]
  #   bindings: ["print_screen+h", "print_screen+left"]
  # - commands: ["focus --direction right"]
  #   bindings: ["print_screen+l", "print_screen+right"]
  # - commands: ["focus --direction up"]
  #   bindings: ["print_screen+k", "print_screen+up"]
  # - commands: ["focus --direction down"]
  #   bindings: ["print_screen+j", "print_screen+down"]

  - commands: ["focus --direction left"]
    bindings: ["print_screen+h"]
  - commands: ["focus --direction right"]
    bindings: ["print_screen+l"]
  - commands: ["focus --direction up"]
    bindings: ["print_screen+k"]
  - commands: ["focus --direction down"]
    bindings: ["print_screen+j"]

  # Move focused window in a given direction.
  - commands: ["move --direction left"]
    bindings: ["print_screen+shift+h", "print_screen+shift+left"]
  - commands: ["move --direction right"]
    bindings: ["print_screen+shift+l", "print_screen+shift+right"]
  - commands: ["move --direction up"]
    bindings: ["print_screen+shift+k", "print_screen+shift+up"]
  - commands: ["move --direction down"]
    bindings: ["print_screen+shift+j", "print_screen+shift+down"]

  # Resize focused window by a percentage or pixel amount.
  - commands: ["resize --width -2%"]
    bindings: ["print_screen+u"]
  - commands: ["resize --width +2%"]
    bindings: ["print_screen+p"]
  - commands: ["resize --height +2%"]
    bindings: ["print_screen+o"]
  - commands: ["resize --height -2%"]
    bindings: ["print_screen+i"]

  # As an print_screenernative to the resize keybindings above, resize mode enables
  # resizing via arrow keys or HJKL. The binding mode is defined above with
  # the name 'resize'.
  - commands: ["wm-enable-binding-mode --name resize"]
    bindings: ["print_screen+r"]

  # Disables window management and all other keybindings until print_screen+shift+p
  # is pressed again.
  - commands: ["wm-toggle-pause"]
    bindings: ["print_screen+shift+p"]

  # Change tiling direction. This determines where new tiling windows will
  # be inserted.
  - commands: ["toggle-tiling-direction"]
    bindings: ["print_screen+v"]

  # Change focus from tiling windows -> floating -> fullscreen.
  # - commands: ["wm-cycle-focus"]
  # bindings: ["print_screen+shift+space"]

  # Change the focused window to be floating.
  - commands: ["toggle-floating --centered"]
    bindings: ["print_screen+shift+space"]

  # Change the focused window to be tiling.
  - commands: ["toggle-tiling"]
    bindings: ["print_screen+t"]

  # Change the focused window to be fullscreen.
  - commands: ["toggle-fullscreen"]
    bindings: ["print_screen+f"]

  # Minimize focused window.
  - commands: ["toggle-minimized"]
    bindings: ["print_screen+m"]

  # Close focused window.
  - commands: ["close"]
    bindings: ["print_screen+q"]

  # Kill GlazeWM process safely.
  - commands: ["wm-exit"]
    bindings: ["print_screen+shift+e"]

  # Re-evaluate configuration file.
  - commands: ["wm-reload-config"]
    bindings: ["print_screen+shift+r"]

  # Redraw all windows.
  - commands: ["wm-redraw"]
    bindings: ["print_screen+shift+w"]

  # Launch CMD terminal. print_screenernatively, use `shell-exec wt` or
  # `shell-exec %ProgramFiles%/Git/git-bash.exe` to start Windows
  # Terminal and Git Bash respectively.
  - commands: ["shell-exec wt"]
    bindings: ["print_screen+enter"]

  # Focus the next/previous active workspace defined in `workspaces` config.
  - commands: ["focus --next-workspace"]
    bindings: ["print_screen+s"]
  - commands: ["focus --prev-workspace"]
    bindings: ["print_screen+a"]

  # Focus the workspace that last had focus.
  - commands: ["focus --recent-workspace"]
    bindings: ["print_screen+d"]

  # Change focus to a workspace defined in `workspaces` config.
  - commands: ["focus --workspace 1"]
    bindings: ["print_screen+1"]
  - commands: ["focus --workspace 2"]
    bindings: ["print_screen+2"]
  - commands: ["focus --workspace 3"]
    bindings: ["print_screen+3"]
  - commands: ["focus --workspace 4"]
    bindings: ["print_screen+4"]
  - commands: ["focus --workspace 5"]
    bindings: ["print_screen+5"]
  - commands: ["focus --workspace 6"]
    bindings: ["print_screen+6"]
  - commands: ["focus --workspace 7"]
    bindings: ["print_screen+7"]
  - commands: ["focus --workspace 8"]
    bindings: ["print_screen+8"]
  - commands: ["focus --workspace 9"]
    bindings: ["print_screen+9"]

  # Move the focused window's parent workspace to a monitor in a given
  # direction.
  - commands: ["move-workspace --direction left"]
    bindings: ["print_screen+shift+a"]
  - commands: ["move-workspace --direction right"]
    bindings: ["print_screen+shift+f"]
  - commands: ["move-workspace --direction up"]
    bindings: ["print_screen+shift+d"]
  - commands: ["move-workspace --direction down"]
    bindings: ["print_screen+shift+s"]

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ["move --workspace 1"]
    bindings: ["print_screen+shift+1"]
  - commands: ["move --workspace 2"]
    bindings: ["print_screen+shift+2"]
  - commands: ["move --workspace 3"]
    bindings: ["print_screen+shift+3"]
  - commands: ["move --workspace 4"]
    bindings: ["print_screen+shift+4"]
  - commands: ["move --workspace 5"]
    bindings: ["print_screen+shift+5"]
  - commands: ["move --workspace 6"]
    bindings: ["print_screen+shift+6"]
  - commands: ["move --workspace 7"]
    bindings: ["print_screen+shift+7"]
  - commands: ["move --workspace 8"]
    bindings: ["print_screen+shift+8"]
  - commands: ["move --workspace 9"]
    bindings: ["print_screen+shift+9"]
