// Generated by Home Manager.

user_pref("app.shield.optoutstudies.enabled", false);
user_pref("browser.aboutConfig.showWarning", false);
user_pref("browser.cache.disk.enable", false);
user_pref("browser.download.always_ask_before_handling_new_types", true);
user_pref("browser.newtabpage.activity-stream.showSponsoredTopSites", false);
user_pref("browser.startup.homepage", "about:home");
user_pref("browser.startup.homepage_override.mstone", "ignore");
user_pref("browser.tabs.unloadOnLowMemory", true);
user_pref("browser.urlbar.showSearchSuggestionsFirst", false);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("datareporting.policy.firstRunURL", "");
user_pref("dom.security.https_only_mode", true);
user_pref("extensions.activeThemeID", "firefox-compact-dark@mozilla.org");
user_pref("extensions.pocket.enabled", false);
user_pref("font.name.monospace.ja", "Noto Sans JP");
user_pref("font.name.sans-serif.ja", "Noto Sans JP");
user_pref("font.name.serif.ja", "Noto Serif JP");
user_pref("media.av1.enabled", false);
user_pref("media.peerconnection.ice.default_address_only", true);
user_pref("network.captive-portal-service.enabled", false);
user_pref("privacy.sanitize.useOldClearHistoryDialog", true);
user_pref("privacy.trackingprotection.enabled", true);
user_pref("sidebar.revamp", true);
// システムのスケールが125%以上の場合にfalseに
user_pref("sidebar.verticalTabs", true);
user_pref("signon.rememberSignons", false);
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("toolkit.telemetry.enabled", false);


